### ISSUE TITLE
please add tags for released version(s)

### ISSUE THREAD

**Issue by sunweaver** [OpenSourcePhysics/osp#3]
Hi,

my name is Mike Gabriel. I am a Debian Developer and plan to bring OSP Core Libs and OSP Tracker to Debian. This means, that OSP Tracker will be available in Debian 10 (and possibly via stable-backports for Debian 9, also).

Normally, uploading software to Debian increases the user base tremendously. I hope this is in your interest. For bring your software cleanly into Debian, I will probably need some help from you upstream people.

First request is this: ideally, I can package OSP software directly from the Git repos on Github. For this to work smoothlessly, I need proper release tags on the Git repositories. So my question: can you at least add the latest version as a git tag to this repository? Thank you!

Mike

**Comment by dobrown** [comment]
Hi Mike, sorry for the long delay. We have now added a version 5.0 tag to OSP core. Tracker 5.0 requires OSP 5.0. Hope this helps!  Doug
